services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - identity
      - job-service
      - moderator-service
      - notification-service
      - user-service
      - application-chat-service
    networks:
      - backend-network

  auth-service:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  identity:
    build:
      context: .
      dockerfile: Identity/Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  job-service:
    build:
      context: .
      dockerfile: JobService/Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  moderator-service:
    build:
      context: .
      dockerfile: ModeratorService/Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  notification-service:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  application-chat-service:
    build:
      context: .
      dockerfile: Application&ChatService/Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 