services:
  auth-service:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  identity:
    build:
      context: .
      dockerfile: Identity/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  job-service:
    build:
      context: .
      dockerfile: JobService/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  moderator-service:
    build:
      context: .
      dockerfile: ModeratorService/Dockerfile
    ports:
      - "8084:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  notification-service:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "8085:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "8086:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  application-chat-service:
    build:
      context: .
      dockerfile: Application&ChatService/Dockerfile
    ports:
      - "8087:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 